package MainProgram;

import Activity.ActivityList;
import ageGroup.view.ManagerAgeGroup;
import InformationOfChild.*;
import UserAndFunctions.frm_UserFunction;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import Nanny.NannyList;
import User.UserList;
import UserAndFunctions.DAO_UserFunction;
import UserAndFunctions.frm_ChangePass;
import javax.swing.JDesktopPane;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import login.LoginUser;
/*
 * MainForm.java
 *
 * Created on June 18, 2009, 10:51 PM
 */

/**
 *
 * @author  Tuong Huy
 */
public class MainForm extends javax.swing.JFrame {

    private static String sConn = "";
    private JDesktopPane desktopPane;
    private static String sAccountName;
    private static int iFullControl = 0;
    private String[] functionCode_AccountName;

    /** Creates new form MainForm */
    public MainForm(String _sConn, Object[] functionList, String _sAccountName) {
        super("Child care system");
        desktopPane = new JDesktopPane();
        this.setContentPane(desktopPane);
        try {
            // Set System L&F
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo.png"));
        Image image = icon.getImage();
        setIconImage(image);
        setExtendedState(MAXIMIZED_BOTH);

        //listFunction = functionList;

        sConn = _sConn;
        sAccountName = _sAccountName;
        try {
            iFullControl = new DAO_UserFunction(sConn).checkIsFullControl(sAccountName);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        setActiveFunctionForUser(functionList);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnbSystem = new javax.swing.JMenuBar();
        mnLogout = new javax.swing.JMenu();
        imn_ManagerAccountInformation = new javax.swing.JMenuItem();
        imn_ProvideManagementFunctionsForUser = new javax.swing.JMenuItem();
        imn_ChangePassword = new javax.swing.JMenuItem();
        imn_Logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        imn_ExitProgram = new javax.swing.JMenuItem();
        mnFunctions = new javax.swing.JMenu();
        imn_ManagerChild = new javax.swing.JMenuItem();
        imn_ManagerAgeGroup = new javax.swing.JMenuItem();
        imn_ManagerNanny = new javax.swing.JMenuItem();
        imn_ManagerActivity = new javax.swing.JMenuItem();
        mnStatistic = new javax.swing.JMenu();
        imn_ListChildByNanny = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Child care system");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainForm.jpg"))); // NOI18N

        mnLogout.setText("System");

        imn_ManagerAccountInformation.setText("Manager login account");
        imn_ManagerAccountInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ManagerAccountInformationActionPerformed(evt);
            }
        });
        mnLogout.add(imn_ManagerAccountInformation);

        imn_ProvideManagementFunctionsForUser.setText("Add/Delete management functions for account");
        imn_ProvideManagementFunctionsForUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ProvideManagementFunctionsForUserActionPerformed(evt);
            }
        });
        mnLogout.add(imn_ProvideManagementFunctionsForUser);

        imn_ChangePassword.setText("Change password of account");
        imn_ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ChangePasswordActionPerformed(evt);
            }
        });
        mnLogout.add(imn_ChangePassword);

        imn_Logout.setText("Log out");
        imn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_LogoutActionPerformed(evt);
            }
        });
        mnLogout.add(imn_Logout);
        mnLogout.add(jSeparator1);

        imn_ExitProgram.setText("Exit");
        imn_ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ExitProgramActionPerformed(evt);
            }
        });
        mnLogout.add(imn_ExitProgram);

        mnbSystem.add(mnLogout);

        mnFunctions.setText("Functions");

        imn_ManagerChild.setText("Manage Child Information");
        imn_ManagerChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ManagerChildActionPerformed(evt);
            }
        });
        mnFunctions.add(imn_ManagerChild);

        imn_ManagerAgeGroup.setText("Manage AgeGroup Information");
        imn_ManagerAgeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ManagerAgeGroupActionPerformed(evt);
            }
        });
        mnFunctions.add(imn_ManagerAgeGroup);

        imn_ManagerNanny.setText("Manage Nanny Information");
        imn_ManagerNanny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ManagerNannyActionPerformed(evt);
            }
        });
        mnFunctions.add(imn_ManagerNanny);

        imn_ManagerActivity.setText("Manage Activity Information");
        imn_ManagerActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ManagerActivityActionPerformed(evt);
            }
        });
        mnFunctions.add(imn_ManagerActivity);

        mnbSystem.add(mnFunctions);

        mnStatistic.setText("Statistic");

        imn_ListChildByNanny.setText("List child by nanny");
        imn_ListChildByNanny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imn_ListChildByNannyActionPerformed(evt);
            }
        });
        mnStatistic.add(imn_ListChildByNanny);

        mnbSystem.add(mnStatistic);

        setJMenuBar(mnbSystem);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //function set Icon for frame
    private void setIconForInternalFrame(String sLogoPath, JInternalFrame internalFrame) {
        ImageIcon icon = new ImageIcon(getClass().getResource(sLogoPath));
        internalFrame.setFrameIcon(icon);
    }

    //menu View Child list group by nanny
    private void imn_ListChildByNannyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ListChildByNannyActionPerformed
        // TODO add your handling code here:
        functionCode_AccountName = new String[]{"4", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frm_Nanny_ChildList = new frm_Nanny_ChildList(sConn);
        setIconForInternalFrame("/images/logo.png", frm_Nanny_ChildList);
        AddForm(frm_Nanny_ChildList, 900, 600, true, true);
    }//GEN-LAST:event_imn_ListChildByNannyActionPerformed

    //menu Add/Remove function for account use system - Only isFullCaontrol can use
    private void imn_ProvideManagementFunctionsForUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ProvideManagementFunctionsForUserActionPerformed
        // TODO add your handling code here:
        functionCode_AccountName = new String[]{"7", sAccountName, Integer.toString(iFullControl)};        
        JInternalFrame frmUserFunction = new frm_UserFunction(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmUserFunction);
        AddForm(frmUserFunction, 900, 600, false, false);
    }//GEN-LAST:event_imn_ProvideManagementFunctionsForUserActionPerformed

    //menu Manager Child Information
    private void imn_ManagerChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ManagerChildActionPerformed
        // TODO add your handling code here:
        //call and view child form
        functionCode_AccountName = new String[]{"1", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frmChildList = new frm_ChildList(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmChildList);
        AddForm(frmChildList, 900, 700, true, true);
    }//GEN-LAST:event_imn_ManagerChildActionPerformed

    //menu Exit program
    private void imn_ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ExitProgramActionPerformed
// TODO add your handling code here:
        try {
            System.exit(0);
        } catch (Exception ex) {
            //
        }
    }//GEN-LAST:event_imn_ExitProgramActionPerformed

    //menu Manager Agegroup Information
    private void imn_ManagerAgeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ManagerAgeGroupActionPerformed
        // TODO add your handling code here:
        functionCode_AccountName = new String[]{"3", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frmManagerAgeGroup = new ManagerAgeGroup(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmManagerAgeGroup);
        AddForm(frmManagerAgeGroup, 600, 500, false, false);

    }//GEN-LAST:event_imn_ManagerAgeGroupActionPerformed

    //menu Manager Activities Information
    private void imn_ManagerActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ManagerActivityActionPerformed
        // TODO add your handling code here:
        functionCode_AccountName = new String[]{"5", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frmManagerActivities = new ActivityList(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmManagerActivities);
        AddForm(frmManagerActivities, 700, 450, false, false);
    }//GEN-LAST:event_imn_ManagerActivityActionPerformed

    //menu Manager Nanny Information
    private void imn_ManagerNannyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ManagerNannyActionPerformed
        // TODO add your handling code here:

        functionCode_AccountName = new String[]{"2", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frmManagerNanny = new NannyList(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmManagerNanny);
        AddForm(frmManagerNanny, 1122, 500, false, false);
    }//GEN-LAST:event_imn_ManagerNannyActionPerformed

    //menu Logout
    private void imn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_LogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginUser(null, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imn_LogoutActionPerformed

    //menu Change Password after login
    private void imn_ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ChangePasswordActionPerformed
        // TODO add your handling code here:
        JInternalFrame frmChangePass = new frm_ChangePass(this, sConn, sAccountName);
        setIconForInternalFrame("/images/logo.png", frmChangePass);
        AddForm(frmChangePass, 395, 203, false, false);
    }//GEN-LAST:event_imn_ChangePasswordActionPerformed

    //menu Manager Account Information
    private void imn_ManagerAccountInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imn_ManagerAccountInformationActionPerformed
        // TODO add your handling code here:
        functionCode_AccountName = new String[]{"6", sAccountName, Integer.toString(iFullControl)};
        JInternalFrame frmLoginAccoutList = new UserList(this, sConn, functionCode_AccountName);
        setIconForInternalFrame("/images/logo.png", frmLoginAccoutList);
        AddForm(frmLoginAccoutList, 700, 450, false, false);
    }//GEN-LAST:event_imn_ManagerAccountInformationActionPerformed

    //Add JInternalFrame to destopPane on MainForm
    private void AddForm(JInternalFrame wnd, int iWidth, int iHeight, boolean reziable, boolean maximizable) {
        boolean isExist = false;
        try {
            for (JInternalFrame frm : desktopPane.getAllFrames()) {
                if (wnd.getTitle().equals(frm.getTitle())) {
                    isExist = true;
                    break;
                }
            }
            if (isExist == true) {
                desktopPane.setSelectedFrame(wnd);
                wnd.setSelected(true);
            } else {
                desktopPane.add(wnd);
                wnd.setResizable(reziable);
                wnd.setClosable(true);
                wnd.setMaximizable(maximizable);
                wnd.setIconifiable(true);
                wnd.setSize(iWidth, iHeight);
                wnd.setVisible(true);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    //Set active with menu that user can use and deactive with menu can't not use
    public void setActiveFunctionForUser(Object[] Function) {
        ArrayList menuList = new ArrayList();
        JMenuItem mnu;
        if (iFullControl == 0) {
            imn_ManagerChild.setEnabled(false);                         // function code=1
            imn_ManagerNanny.setEnabled(false);
            imn_ManagerAgeGroup.setEnabled(false);                      // function code=3
            imn_ListChildByNanny.setEnabled(false);
            imn_ManagerActivity.setEnabled(false);
            imn_ManagerAccountInformation.setEnabled(false);
            imn_ProvideManagementFunctionsForUser.setEnabled(false);


            menuList.add(imn_ManagerChild);
            menuList.add(imn_ManagerNanny);
            menuList.add(imn_ManagerAgeGroup);
            menuList.add(imn_ListChildByNanny);
            menuList.add(imn_ManagerActivity);
            menuList.add(imn_ManagerAccountInformation);
            menuList.add(imn_ProvideManagementFunctionsForUser);

            int k;
            for (int i = 0; i < Function.length; i++) {
                mnu = new JMenuItem();
                k = Integer.parseInt(Function[i].toString());
                mnu = (JMenuItem) menuList.get(k - 1);
                mnu.setEnabled(true);
            }
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imn_ChangePassword;
    private javax.swing.JMenuItem imn_ExitProgram;
    private javax.swing.JMenuItem imn_ListChildByNanny;
    private javax.swing.JMenuItem imn_Logout;
    private javax.swing.JMenuItem imn_ManagerAccountInformation;
    private javax.swing.JMenuItem imn_ManagerActivity;
    private javax.swing.JMenuItem imn_ManagerAgeGroup;
    private javax.swing.JMenuItem imn_ManagerChild;
    private javax.swing.JMenuItem imn_ManagerNanny;
    private javax.swing.JMenuItem imn_ProvideManagementFunctionsForUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu mnFunctions;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenu mnStatistic;
    private javax.swing.JMenuBar mnbSystem;
    // End of variables declaration//GEN-END:variables
}
