package Nanny;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author CristianoT
 */
public class AddDialog extends javax.swing.JDialog {

    String sConn = null;
    private DataAccessTable dao;

    /** Creates new form AddDialog */
    public AddDialog(java.awt.Frame parent, boolean modal, String sConn) {
        super(parent, modal);
        initComponents();
        this.sConn = sConn;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtYearOfBirth = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtCharge = new javax.swing.JTextField();
        txtWorkingHours = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtChildAssignedToHer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAddress = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Nanny");

        jLabel1.setFont(new java.awt.Font("VNI-Present", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ADD NANNY");

        jLabel6.setText("Child :");

        jLabel7.setText("Mail :");

        jLabel8.setText("Working Hours :");

        txaAddress.setColumns(20);
        txaAddress.setRows(5);
        jScrollPane1.setViewportView(txaAddress);

        jLabel10.setText("Address :");

        jLabel5.setText("Charge :");

        jLabel4.setText("Phone :");

        jLabel3.setText("Year Of Birth :");

        jLabel2.setText("Name :");

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok1.png"))); // NOI18N
        btnOk.setText("Ok   ");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close2.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtYearOfBirth)
                                    .addComponent(txtPhone)
                                    .addComponent(txtCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtChildAssignedToHer)
                                    .addComponent(txtMail)
                                    .addComponent(txtWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChildAssignedToHer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnReset)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
        String message = "Enter the following detail(s) correctly: \n";

        if (txtName.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's name. Please !! \n";
        }

        try {
            if (new Business("tbl_Nanny", sConn).checkActivity("tbl_Nanny", txtName.getText().trim()).next()) {
                message += "- Nanny's name exists !!! \n";
                flag = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        int year = 0;

        if (txtYearOfBirth.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's birthyear. Please !! \n";
        }else{
            year = Integer.parseInt(txtYearOfBirth.getText());
        }


        if (txtYearOfBirth.getText().length() != 4) {
            flag = false;
            message += "- Nanny's birthyear must be 4 characters !! \n";
            txtYearOfBirth.requestFocus(true);
            txtYearOfBirth.selectAll();
        }
        if (txaAddress.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's address. Please !! \n";
        }
        if (txtPhone.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's phone. Please !! \n";
        }
        if (txtMail.getText().equals("")) {
            flag = false;
            message += "- Nanny's email. Please !! \n";
        }
        if (txtPhone.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's phone. Please !! \n";
        }
        if (txtCharge.getText().trim().equals("")) {
            flag = false;
            message += "- Charge paid to her. Please !! \n";
        }
        if (txtWorkingHours.getText().trim().equals("")) {
            flag = false;
            message += "- Nanny's wokinghours. Please !! \n";
        }
        if (txtChildAssignedToHer.getText().trim().equals("")) {
            flag = false;
            message += "- Child assigned to her. Please !! \n";
        } else if (!validateNumber(txtYearOfBirth.getText())) {
            flag = false;
            message += "- Year Of Birth must be a number !!!";
        } else if (year < 1970 || year > 1990) {
            flag = false;
            message += "- Nanny's birthyear must be between 1970 & 1990 !! \n";
            txtYearOfBirth.requestFocus(true);
            txtYearOfBirth.selectAll();
        } else if (!validateNumber(txtCharge.getText())) {
            flag = false;
            message += "- Charge must be a number !!!";
        } else if (!validateNumber(txtWorkingHours.getText())) {
            flag = false;
            message += "- WorkingHours must be a number !!!";
        } else if (!validateNumber(txtChildAssignedToHer.getText())) {
            flag = false;
            message += "- Child Assigned to Her must be a number !!!";
        }
        try {
            if (new Business("tbl_Nanny", sConn).checkActivity("tbl_Nanny", txtName.getText().trim()).next()) {
                message += "- Nanny's name exists !!!";
                flag = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (flag) {
            int choice = JOptionPane.showConfirmDialog(this, "This nanny will be added to your database after press YES !!!", "Add Nanny", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                Double doubleCharge = Double.parseDouble(txtCharge.getText());
                Integer intChildAssignedToHer = Integer.parseInt(txtChildAssignedToHer.getText());
                Integer intWorkingHours = Integer.parseInt(txtWorkingHours.getText());
                Integer intYearOfBirth = Integer.parseInt(txtYearOfBirth.getText());
                Entity nanny = new Entity(txtName.getText(), intYearOfBirth, txaAddress.getText(), txtPhone.getText(), txtMail.getText(), doubleCharge, intWorkingHours, intChildAssignedToHer);
                DataAccessTable dao = new DataAccessTable(message, sConn);
                dao.insert(nanny);
                this.setVisible(false);
            } else {
                return;
            }
        } else {
            JOptionPane.showConfirmDialog(this, message, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private static Boolean validateNumber(String strNumber) {
        try {
            Double.parseDouble(strNumber);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    /**/

    /**
     * @param args the command line arguments
     */
    private void resetForm() {
        txtName.setText("");
        txtChildAssignedToHer.setText("");
        txtYearOfBirth.setText("");
        txtCharge.setText("");
        txtPhone.setText("");
        txtMail.setText("");
        txaAddress.setText("");
        txtWorkingHours.setText("");
        txtChildAssignedToHer.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaAddress;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtChildAssignedToHer;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWorkingHours;
    private javax.swing.JTextField txtYearOfBirth;
    // End of variables declaration//GEN-END:variables
}
