package login;

import MainProgram.MainForm;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DThanh
 */
public class LoginUser extends javax.swing.JDialog {

    private LoginInfo logininfor;
    private DAO_Login daologin;
    private Object[] configInfo;
    private String urlDriver = "jdbc:sqlserver://";
    private String databaseName = "ChildCare";

    /** Creates new form ConfigServer */
    public LoginUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo.png"));
        Image image = icon.getImage();
        setIconImage(image);
        logininfor = new LoginInfo();
        daologin = new DAO_Login();

        //check file config
        try {
            if (daologin.checkFile("login.txt")) {
                configInfo = daologin.getConfig("login.txt");

                if (configInfo != null && configInfo.length >= 3) {
                    txtServerName.setText(configInfo[0].toString());
                    txtUserDatabase.setText(configInfo[2].toString());
                    txtPasswordDatabase.setText(configInfo[3].toString());

                    logininfor.setDatabaseName(databaseName);
                    logininfor.setServerName(configInfo[0].toString());
                    logininfor.setUserName(configInfo[2].toString());
                    logininfor.setPassword(configInfo[3].toString());
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        pnlData = new javax.swing.JPanel();
        lblImages1 = new javax.swing.JLabel();
        pnlDataDetails = new javax.swing.JPanel();
        lblServerName = new javax.swing.JLabel();
        txtServerName = new javax.swing.JTextField();
        lblUserData = new javax.swing.JLabel();
        txtUserDatabase = new javax.swing.JTextField();
        lblPasswordData = new javax.swing.JLabel();
        txtPasswordDatabase = new javax.swing.JPasswordField();
        pnlUser = new javax.swing.JPanel();
        lblImages2 = new javax.swing.JLabel();
        pnlDetailsUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblMessage = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login form");
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeader.setText("Login User");
        lblHeader.setPreferredSize(new java.awt.Dimension(350, 30));
        getContentPane().add(lblHeader);

        pnlData.setBorder(javax.swing.BorderFactory.createTitledBorder("Database"));
        pnlData.setPreferredSize(new java.awt.Dimension(370, 150));

        lblImages1.setPreferredSize(new java.awt.Dimension(90, 100));
        pnlData.add(lblImages1);

        pnlDataDetails.setPreferredSize(new java.awt.Dimension(250, 80));

        lblServerName.setText("Server name :");
        lblServerName.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlDataDetails.add(lblServerName);

        txtServerName.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlDataDetails.add(txtServerName);

        lblUserData.setText("User name :");
        lblUserData.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlDataDetails.add(lblUserData);

        txtUserDatabase.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlDataDetails.add(txtUserDatabase);

        lblPasswordData.setText("Password :");
        lblPasswordData.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlDataDetails.add(lblPasswordData);

        txtPasswordDatabase.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlDataDetails.add(txtPasswordDatabase);

        pnlData.add(pnlDataDetails);

        getContentPane().add(pnlData);

        pnlUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User ID"));
        pnlUser.setPreferredSize(new java.awt.Dimension(370, 120));

        lblImages2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png"))); // NOI18N
        lblImages2.setPreferredSize(new java.awt.Dimension(90, 70));
        pnlUser.add(lblImages2);

        pnlDetailsUser.setPreferredSize(new java.awt.Dimension(250, 80));

        lblUser.setText("User ID:");
        lblUser.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlDetailsUser.add(lblUser);

        txtUser.setText("administrator");
        txtUser.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlDetailsUser.add(txtUser);

        lblPassword.setText("Password:");
        lblPassword.setPreferredSize(new java.awt.Dimension(80, 20));
        pnlDetailsUser.add(lblPassword);

        txtPassword.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlDetailsUser.add(txtPassword);

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblMessage.setPreferredSize(new java.awt.Dimension(130, 20));
        pnlDetailsUser.add(lblMessage);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        btnOk.setText("Login");
        btnOk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOk.setPreferredSize(new java.awt.Dimension(100, 23));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlDetailsUser.add(btnOk);

        pnlUser.add(pnlDetailsUser);

        getContentPane().add(pnlUser);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-400)/2, 400, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:

        String sDatabsePassword = new String(txtPasswordDatabase.getPassword());
        String sUserPassword = new String(txtPassword.getPassword());

        // Check input login to database
        if (txtServerName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please, Enter the server name.");
            return;
        }

        if (txtUserDatabase.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please, Enter the database login username.");
            return;
        }

        if (sDatabsePassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please, Enter the database password login.");
            return;
        }

        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please, Enter UserName login to ChildCare system.");
            return;
        }

        if (sUserPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Please, Enter the password for username login to ChildCare system.");
            return;
        }

        urlDriver += txtServerName.getText() + ";databaseName=" + databaseName +
                ";user=" + txtUserDatabase.getText() + ";password=" + sDatabsePassword;
        try {
            Connection connection = null;
            daologin.setConnectionString(urlDriver);
            connection = daologin.CreateConnection();

            if (connection != null) {
                //compare data read from file and user data inputed
                if (!logininfor.getServerName().equals(txtServerName.getText()) ||
                        !logininfor.getUserName().equals(txtUserDatabase.getText()) ||
                        !logininfor.getPassword().equals(sDatabsePassword)) {

                    logininfor.setDatabaseName(databaseName);
                    logininfor.setServerName(txtServerName.getText());
                    logininfor.setUserName(txtUserDatabase.getText());
                    logininfor.setPassword(sDatabsePassword);

                    daologin.saveConfig(logininfor, "login.txt");
                }
                //do login
                Object[] listFunction = daologin.DoLogin(txtUser.getText(), sUserPassword);
                if (listFunction == null || listFunction.length <= 0) {
                    JOptionPane.showMessageDialog(this, "Your account not exist or Password is wrong or It has not been granted access to the system.");
                } else {
                    this.setVisible(false);
                    new MainForm(urlDriver, listFunction, txtUser.getText()).setVisible(true);
                    this.dispose();
                }

            } else {
                JOptionPane.showConfirmDialog(this, "Cannot connect to database", "Error", JOptionPane.CLOSED_OPTION);
                return;
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Cannot connect to database", "Error", JOptionPane.CLOSED_OPTION);
        }
}//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LoginUser dialog = new LoginUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblImages1;
    private javax.swing.JLabel lblImages2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordData;
    private javax.swing.JLabel lblServerName;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserData;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlDataDetails;
    private javax.swing.JPanel pnlDetailsUser;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordDatabase;
    private javax.swing.JTextField txtServerName;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserDatabase;
    // End of variables declaration//GEN-END:variables
}
