package ageGroup.view;

import ageGroup.dataObject.AgeGroupDAO;
import ageGroup.valuesObject.AgeGroupVO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DThanh
 */
public class DetailsAgeGroup extends javax.swing.JDialog {

    /** Creates new form DetailsAgeGroup */
    public DetailsAgeGroup(java.awt.Frame parent, boolean modal, AgeGroupVO ageVO, String connect) {
        super(parent, modal);

        this.strConnect = connect;
        this.ageVO = ageVO;

        ageDO = new AgeGroupDAO(connect);

        try {
            array = ageDO.showActivitySelected(ageVO.getAgeCode());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        initComponents();
        txtChildAge.setText(ageVO.getChildAge());
        txtCharge.setText(ageVO.getCharges().toString());
        for (int i = 0; i < array.size(); i++) {
            selected += array.get(i) + "\n";
        }
        txaActivity.setText(selected);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblChildAgeGroup = new javax.swing.JLabel();
        txtChildAge = new javax.swing.JTextField();
        lblCharge = new javax.swing.JLabel();
        txtCharge = new javax.swing.JTextField();
        scpActivity = new javax.swing.JScrollPane();
        txaActivity = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail age group");
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeader.setText("View details");
        lblHeader.setPreferredSize(new java.awt.Dimension(380, 29));
        getContentPane().add(lblHeader);

        jPanel1.setPreferredSize(new java.awt.Dimension(380, 70));

        lblChildAgeGroup.setText("Child age group:");
        lblChildAgeGroup.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(lblChildAgeGroup);

        txtChildAge.setText("Age 2 to 5 year");
        txtChildAge.setEnabled(false);
        txtChildAge.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(txtChildAge);

        lblCharge.setText("Charges as per the group:");
        lblCharge.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(lblCharge);

        txtCharge.setText("105");
        txtCharge.setEnabled(false);
        txtCharge.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(txtCharge);

        getContentPane().add(jPanel1);

        scpActivity.setPreferredSize(new java.awt.Dimension(380, 100));

        txaActivity.setColumns(20);
        txaActivity.setEditable(false);
        txaActivity.setRows(5);
        txaActivity.setPreferredSize(new java.awt.Dimension(360, 200));
        scpActivity.setViewportView(txaActivity);

        getContentPane().add(scpActivity);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(100, 23));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);

        btnSelect.setText("Select activity");
        btnSelect.setPreferredSize(new java.awt.Dimension(100, 23));
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close2.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 23));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-350)/2, 400, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //methodt getSelectdColumn(),getSelectedRow() Tra ve index column,row
        new AddEditlForm(null, rootPaneCheckingEnabled, "Edit age group", ageVO, strConnect).setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_btnEditActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you exit?", "Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        new SelectActivities(null, rootPaneCheckingEnabled, strConnect, ageVO).setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_btnSelectActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCharge;
    private javax.swing.JLabel lblChildAgeGroup;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scpActivity;
    private javax.swing.JTextArea txaActivity;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtChildAge;
    // End of variables declaration//GEN-END:variables
    private String strConnect = "";
    private AgeGroupVO ageVO = null;
    private AgeGroupDAO ageDO;
    private ArrayList array;
    private String selected = "Activities selected : \n";
}
