package ageGroup.view;

import MainProgram.MainForm;
import UserAndFunctions.DAO_UserFunction;
import java.sql.SQLException;
import ageGroup.business.*;
import ageGroup.valuesObject.AgeGroupVO;
import javax.swing.JOptionPane;

/**
 *
 * @author DThanh
 */
public class ManagerAgeGroup extends javax.swing.JInternalFrame {
    private String[] sFunctionCode_AccountName;     //get permistion
    private Object[] oPermistionList;               //Array with 3 element: add, delete, edit
    int selectRow_=-1;


    /** Creates new form ManagerAgeGroup */
    public ManagerAgeGroup(java.awt.Frame parent, String _sConn, String[] _sFunctionCode_Account) {
        sConn = _sConn;
        main = (MainForm) parent;
        ageManager = new AgeGroupManager(sConn);
        sFunctionCode_AccountName=_sFunctionCode_Account;

        try {
            model = new MyTableModel(sConn, "tbl_AgeGroup");
            DAO_UserFunction daouser = new DAO_UserFunction(sConn);
            oPermistionList = daouser.getPermistionList(sFunctionCode_AccountName[1].toString(), Integer.parseInt(sFunctionCode_AccountName[0].toString()));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        initComponents();
        ActiveButton();
    }

    private void ActiveButton() {
        if (Integer.parseInt(sFunctionCode_AccountName[2]) == 0) {
            // Add permistion
            if (Integer.parseInt(oPermistionList[0].toString()) == 1) {
                btnAdd.setEnabled(true);
            } else {
                btnAdd.setEnabled(false);
            }

            //Edit permistion
            if (Integer.parseInt(oPermistionList[1].toString()) == 1) {
                if(selectRow_!=-1){
                    btnEdit.setEnabled(true);
                    btnView.setEnabled(true);
                }
                else{
                    btnEdit.setEnabled(false);
                    btnView.setEnabled(false);
                }
            } else {
                btnEdit.setEnabled(false);
                btnView.setEnabled(false);
            }

            // Delete permistion
            if (Integer.parseInt(oPermistionList[2].toString()) == 1) {
                if(selectRow_!=-1){
                    btnDelete.setEnabled(true);
                }
                else{
                    btnDelete.setEnabled(false);
                }
            } else {
                btnDelete.setEnabled(false);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scpAgeGroup = new javax.swing.JScrollPane();
        tblAgeGroup = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setTitle("Manager Age Group");
        getContentPane().setLayout(new java.awt.FlowLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Manager Age Group");
        lblHeader.setPreferredSize(new java.awt.Dimension(550, 40));
        getContentPane().add(lblHeader);

        scpAgeGroup.setPreferredSize(new java.awt.Dimension(550, 200));

        tblAgeGroup.setModel(model);
        tblAgeGroup.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAgeGroup.getTableHeader().setReorderingAllowed(false);
        tblAgeGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAgeGroupMousePressed(evt);
            }
        });
        scpAgeGroup.setViewportView(tblAgeGroup);

        getContentPane().add(scpAgeGroup);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Add...");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Edit...");
        btnEdit.setPreferredSize(new java.awt.Dimension(100, 23));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detail.png"))); // NOI18N
        btnView.setText("View Details...");
        btnView.setPreferredSize(new java.awt.Dimension(130, 23));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnView);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-500)/2, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AgeGroupVO ageVO = null;
        new AddEditlForm(main, rootPaneCheckingEnabled, "Add new age group", ageVO, sConn).setVisible(true);
        refreshModel();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        selectRow_ = -1;
        selectRow_ = tblAgeGroup.getSelectedRow();

        if (selectRow_ != -1) {
            //methodt getSelectdColumn(),getSelectedRow() Tra ve index column,row
            int ageCode_ = Integer.parseInt(tblAgeGroup.getValueAt(selectRow_, 0).toString());
            String childAge_ = tblAgeGroup.getValueAt(selectRow_, 1).toString();
            Double charge_ = Double.parseDouble(tblAgeGroup.getValueAt(selectRow_, 2).toString());

            AgeGroupVO ageVO = new AgeGroupVO(ageCode_, childAge_, charge_);
            new AddEditlForm(main, rootPaneCheckingEnabled, "Edit age group", ageVO, sConn).setVisible(true);

            refreshModel();
        } else if (selectRow_ == -1) {
            JOptionPane.showMessageDialog(this, "You have must be select the a row in table list below.");
            return;
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblAgeGroupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgeGroupMousePressed
        // TODO add your handling code here:
        selectRow_=tblAgeGroup.getSelectedRow();
        ActiveButton();
    }//GEN-LAST:event_tblAgeGroupMousePressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        selectRow_ = -1;
        selectRow_ = tblAgeGroup.getSelectedRow();
        if (selectRow_ != -1) {
            int choice = JOptionPane.showConfirmDialog(this, "Are you delete this row? This take effect to another table!!", "Wanning",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choice == JOptionPane.YES_OPTION) {
                //methodt getSelectdColumn(),getSelectedRow() Tra ve index column,row
                int ageCode_ = Integer.parseInt(tblAgeGroup.getValueAt(selectRow_, 0).toString());
                String childAge_ = tblAgeGroup.getValueAt(selectRow_, 1).toString();
                Double charge_ = Double.parseDouble(tblAgeGroup.getValueAt(selectRow_, 2).toString());

                AgeGroupVO ageVO = new AgeGroupVO(ageCode_, childAge_, charge_);
                ageManager.deleteData(ageVO);
                refreshModel();
            }
        } else if (selectRow_ == -1) {
            JOptionPane.showMessageDialog(this, "You have must be select the a row in table list below.");
            return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        selectRow_ = -1;
        selectRow_ = tblAgeGroup.getSelectedRow();
        if (selectRow_ != -1) {

            int ageCode_ = Integer.parseInt(tblAgeGroup.getValueAt(selectRow_, 0).toString());
            String childAge_ = tblAgeGroup.getValueAt(selectRow_, 1).toString();
            Double charge_ = Double.parseDouble(tblAgeGroup.getValueAt(selectRow_, 2).toString());

            AgeGroupVO ageVO = new AgeGroupVO(ageCode_, childAge_, charge_);

            new DetailsAgeGroup(main, rootPaneCheckingEnabled, ageVO, sConn).setVisible(true);

            refreshModel();
        } else if (selectRow_ == -1) {
            JOptionPane.showMessageDialog(this, "You have must be select the a row in table list below.");
            return;
        }
    }//GEN-LAST:event_btnViewActionPerformed

    public void refreshModel() {
        try {
            model = new MyTableModel(sConn, "tbl_AgeGroup");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        tblAgeGroup.setModel(model);
        scpAgeGroup.setViewportView(tblAgeGroup);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scpAgeGroup;
    private javax.swing.JTable tblAgeGroup;
    // End of variables declaration//GEN-END:variables
    private MyTableModel model;
    private AgeGroupManager ageManager;
    private static MainForm main = null;
    private String sConn = "";
}
